---
name: "reseq"
description: Generates synthetic data based on the reference genome and reads.
keywords:
  - simulation
  - genomics
  - data
tools:
  - "reseq":
      description: "ReSeq Illumina/BGI simulator"
      homepage: "https://github.com/schmeing/ReSeq"
      documentation: "https://github.com/schmeing/ReSeq"
      tool_dev_url: "https://github.com/schmeing/ReSeq"
      doi: "10.1186/s13059-021-02265-7"
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - fasta:
      type: file
      description: Reference genome file in fasta format
      pattern: "*.{fasta}"
  - bam:
      type: file
      description: Sorted BAM file
      pattern: "*.{bam}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - simulated_fastqgz:
      type: file
      description: Simulated reads as two matching fastq.gz files
      pattern: "*.{fastq.gz}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@aperz"
maintainers:
  - "@aperz"
